# ============================================================
# AI coding-assistant guide installer
# ============================================================
# `install_agent_guide()` writes a hierarchical, version-stamped guide to the whole
# JuliaSMLM ecosystem into a repo (or the user's home) so a coding assistant (Claude
# Code or Codex) has the APIs of SMLMAnalysis and every sub-package on hand.
#
# The content is assembled at call time from the versions RESOLVED in the current
# environment — each package's `api_overview.md` (falling back to README) is read
# from its `pkgdir`, so the guide never drifts from what is actually installed.

# Ordered ecosystem package list (module => one-line role). SMLMAnalysis itself is
# prepended in _collect_pkg_docs as the integration layer. Order mirrors the
# dependency hierarchy: core types first, then the single-step packages, then the
# higher-level grouping/clustering packages.
_ecosystem_packages() = (
    (SMLMData,            "Core types shared by every package: Emitter2D/3D(Fit), Camera, BasicSMLD, ROIBatch"),
    (SMLMBoxer,           "ROI detection from raw camera images (difference-of-Gaussians)"),
    (GaussMLE,            "GPU-accelerated maximum-likelihood PSF fitting (Gaussian/astigmatic models)"),
    (MicroscopePSFs,      "PSF models: Gaussian, Airy, spline, and vector PSFs"),
    (SMLMSim,             "SMLM data simulation and fluorophore blinking kinetics"),
    (SMLMFrameConnection, "Linking localizations across frames + uncertainty calibration"),
    (SMLMDriftCorrection, "Sample-drift correction (entropy-based) and cross-channel alignment"),
    (SMLMRender,          "Super-resolution image rendering (histogram/Gaussian/circle/ellipse)"),
    (SMLMClustering,      "Clustering backends, spatial-tendency statistics, and edge classification"),
    (SMLMBaGoL,           "Bayesian grouping of localizations into high-precision emitters (RJMCMC)"),
)

# Faithful to the hierarchy in CLAUDE.md / README.
_dependency_tree() = """
SMLMData  (core types — no deps)
   |
   +-- SMLMBoxer ----+
   +-- GaussMLE -----+--- detection + fitting
   +-- MicroscopePSFs --- SMLMSim   (simulation)
   +-- SMLMFrameConnection
   +-- SMLMDriftCorrection
   +-- SMLMRender
   +-- SMLMClustering ---- SMLMBaGoL (Bayesian grouping)
   |
SMLMAnalysis  (integrates all of the above into one analyze() pipeline)
"""

# Single-line YAML description for the Claude skill frontmatter (also used as the
# lead line of the Codex guide). Kept free of `: ` so it is a safe YAML plain scalar.
_guide_description() = "JuliaSMLM SMLM analysis ecosystem — the unified analyze() pipeline (detect, fit, filter, frame-connect, drift-correct, render, cluster, BaGoL) plus the full APIs of every sub-package. Use when writing or debugging single-molecule-localization-microscopy code with SMLMAnalysis.jl or any JuliaSMLM package."

# --- content collection --------------------------------------------------------

function _pkg_entry(mod::Module, role::AbstractString)
    name = string(nameof(mod))
    root = pkgdir(mod)
    ver  = try string(pkgversion(mod)) catch; "unknown" end
    (text, source) = _read_api_text(root, name)
    (; name, role, version = ver, text, source)
end

# api_overview.md is the ecosystem's AI-parseable reference convention; README is the
# fallback. Returns (text, source_label).
function _read_api_text(root::Union{AbstractString,Nothing}, name::AbstractString)
    root === nothing && return ("_(package directory for $name not found)_\n", "none")
    for fname in ("api_overview.md", "README.md")
        p = joinpath(root, fname)
        isfile(p) && return (read(p, String), fname)
    end
    ("_(no api_overview.md or README.md found for $name)_\n", "none")
end

function _collect_pkg_docs()
    entries = Any[_pkg_entry(@__MODULE__,
        "Integration layer — the unified analyze(state, config) pipeline that orchestrates every package below")]
    for (mod, role) in _ecosystem_packages()
        push!(entries, _pkg_entry(mod, role))
    end
    entries
end

# --- rendering -----------------------------------------------------------------

function _render_guide(entries, refprefix::AbstractString)
    io = IOBuffer()
    println(io, "# SMLMAnalysis — JuliaSMLM ecosystem API guide")
    println(io)
    println(io, "Generated by `SMLMAnalysis.install_agent_guide()` from the package versions ",
                "resolved in this environment. Re-run it to refresh.")
    println(io)
    println(io, "SMLMAnalysis integrates the JuliaSMLM single-molecule-localization-microscopy ",
                "packages into one `analyze(state, config)` pipeline: the config type selects the ",
                "operation via multiple dispatch, and steps compose in any order after detection/fitting. ",
                "Coordinates are in microns throughout; raw data is `(height, width, frames)` image stacks.")
    println(io)
    println(io, "## Dependency hierarchy")
    println(io, "```")
    print(io, _dependency_tree())
    println(io, "```")
    println(io)
    println(io, "## Packages (versions resolved in this environment)")
    println(io)
    for e in entries
        println(io, "- **$(e.name)** `v$(e.version)` — $(e.role)  ")
        println(io, "  Full API: [`$(refprefix)/$(e.name).md`]($(refprefix)/$(e.name).md) *(source: $(e.source))*")
    end
    println(io)
    println(io, "## Where to start")
    println(io, "- Entry point: `analyze(image_stacks, AnalysisConfig(...))`, or step-by-step ",
                "`analyze(state, SomeConfig())`.")
    println(io, "- Full SMLMAnalysis API (pipeline, step configs, I/O, multi-target): see ",
                "[`$(refprefix)/SMLMAnalysis.md`]($(refprefix)/SMLMAnalysis.md).")
    println(io, "- Each `reference/*.md` above is that package's own `api_overview.md`, copied verbatim.")
    String(take!(io))
end

function _write_reference!(refdir::AbstractString, e)
    mkpath(refdir)
    p = joinpath(refdir, e.name * ".md")
    open(p, "w") do io
        println(io, "<!-- $(e.name) v$(e.version) — copied from $(e.source) by ",
                    "SMLMAnalysis.install_agent_guide(). Do not edit; re-run to refresh. -->")
        println(io)
        print(io, e.text)
    end
    p
end

# --- git / AGENTS.md side effects ----------------------------------------------

# Append patterns to <root>/.gitignore (creating it if needed), skipping any already
# present. Preserves a missing trailing newline in the existing file.
function _ensure_gitignored!(root::AbstractString, patterns)
    gi   = joinpath(root, ".gitignore")
    raw  = isfile(gi) ? read(gi, String) : ""
    have = Set(strip.(split(raw, '\n')))
    todo = [p for p in patterns if !(strip(p) in have)]
    isempty(todo) && return gi
    buf = raw
    isempty(buf) || endswith(buf, '\n') || (buf *= '\n')
    isempty(buf) || (buf *= '\n')
    buf *= "# SMLMAnalysis agent guide — installed with track=false (install_agent_guide)\n"
    buf *= join(todo, '\n') * '\n'
    write(gi, buf)
    gi
end

const _AGENTS_BEGIN = "<!-- BEGIN SMLMAnalysis agent guide (managed by install_agent_guide) -->"
const _AGENTS_END   = "<!-- END SMLMAnalysis agent guide -->"

# Insert or replace our delimited block in AGENTS.md, leaving any other content
# untouched. Idempotent: re-running refreshes the block in place.
function _upsert_agents_block!(path::AbstractString, block::AbstractString)
    raw     = isfile(path) ? read(path, String) : ""
    managed = string(_AGENTS_BEGIN, '\n', block, '\n', _AGENTS_END)
    b = findfirst(_AGENTS_BEGIN, raw)
    e = findfirst(_AGENTS_END, raw)
    if b !== nothing && e !== nothing && first(e) > first(b)
        newraw = raw[1:prevind(raw, first(b))] * managed * raw[nextind(raw, last(e)):end]
        write(path, newraw)
    else
        buf = raw
        isempty(buf) || endswith(buf, '\n') || (buf *= '\n')
        isempty(buf) || (buf *= '\n')
        write(path, buf * managed * '\n')
    end
    path
end

# --- public entry point --------------------------------------------------------

"""
    install_agent_guide(; tool=:claude, scope=:project, track=false,
                          overwrite=false, dir=pwd()) -> String

Install a hierarchical, version-stamped guide to the JuliaSMLM ecosystem for an AI
coding assistant, so it has the APIs of `SMLMAnalysis` and every sub-package on hand.

The guide is assembled at call time from the versions resolved in the current
environment — each package's `api_overview.md` (falling back to `README.md`) is read
from its `pkgdir` and copied into a `reference/` bundle, with a top-level map linking
them. Re-running refreshes it against whatever is currently installed.

# Keyword arguments
- `tool::Symbol = :claude` — target assistant:
  - `:claude` writes a Claude Code **skill** (`SKILL.md` + `reference/*.md`).
  - `:codex` writes a `smlm-agent-guide/` bundle and adds a pointer block to `AGENTS.md`.
- `scope::Symbol = :project` — where it lands:
  - `:project` → into `dir` (the repo): `.claude/skills/smlmanalysis/` or `./AGENTS.md`.
  - `:user` → into your home: `~/.claude/skills/smlmanalysis/` or `~/.codex/AGENTS.md`
    (applies to every project you open).
- `track::Bool = false` — **project scope only.** When `false` (default) the installed
  files are added to the repo's `.gitignore`, keeping the guide out of history. Pass
  `track=true` to commit and share it with the repo. Ignored (with a warning) for
  `scope=:user`.
- `overwrite::Bool = false` — refresh an existing install in place. Without it, an
  existing guide raises an error rather than being clobbered.
- `dir::AbstractString = pwd()` — the repo root for `scope=:project` (defaults to the
  current directory).

Returns the path of the installed skill/bundle directory.

# Examples
```julia
using SMLMAnalysis
install_agent_guide()                                   # Claude skill in ./.claude, gitignored
install_agent_guide(track=true)                         # …and committed to the repo
install_agent_guide(tool=:codex)                        # Codex AGENTS.md + bundle in this repo
install_agent_guide(scope=:user)                        # Claude skill for all your projects
```
"""
function install_agent_guide(; tool::Symbol = :claude,
                               scope::Symbol = :project,
                               track::Bool = false,
                               overwrite::Bool = false,
                               dir::AbstractString = pwd())
    tool in (:claude, :codex) ||
        throw(ArgumentError("tool must be :claude or :codex, got :$tool"))
    scope in (:project, :user) ||
        throw(ArgumentError("scope must be :project or :user, got :$scope"))
    if track && scope == :user
        @warn "track applies only to scope=:project (the :user guide lives outside any repo); ignoring track=true"
    end

    entries    = _collect_pkg_docs()
    gitignore  = !track && scope == :project

    if tool == :claude
        skill_dir = scope == :project ?
            joinpath(dir, ".claude", "skills", "smlmanalysis") :
            joinpath(homedir(), ".claude", "skills", "smlmanalysis")
        wrapper = joinpath(skill_dir, "SKILL.md")
        if isfile(wrapper) && !overwrite
            error("A Claude skill is already installed at $skill_dir. Pass overwrite=true to refresh it.")
        end
        refdir = joinpath(skill_dir, "reference")
        isdir(refdir) && rm(refdir; recursive = true)
        mkpath(refdir)
        for e in entries
            _write_reference!(refdir, e)
        end
        frontmatter = string("---\nname: smlmanalysis\ndescription: \"",
                             _guide_description(), "\"\n---\n\n")
        write(wrapper, frontmatter * _render_guide(entries, "reference"))
        gitignore && _ensure_gitignored!(dir, ["/.claude/skills/smlmanalysis/"])
        return skill_dir
    else # :codex
        base       = scope == :project ? String(dir) : joinpath(homedir(), ".codex")
        bundle_dir = joinpath(base, "smlm-agent-guide")
        agents     = joinpath(base, "AGENTS.md")
        refdir     = joinpath(bundle_dir, "reference")
        if isfile(joinpath(bundle_dir, "GUIDE.md")) && !overwrite
            error("A Codex guide is already installed at $bundle_dir. Pass overwrite=true to refresh it.")
        end
        isdir(refdir) && rm(refdir; recursive = true)
        mkpath(refdir)
        for e in entries
            _write_reference!(refdir, e)
        end
        write(joinpath(bundle_dir, "GUIDE.md"), _render_guide(entries, "reference"))
        block = string(_guide_description(), "\n\n",
                       "When working with JuliaSMLM / SMLMAnalysis code, read the ecosystem guide at ",
                       "`smlm-agent-guide/GUIDE.md` and the per-package API references under ",
                       "`smlm-agent-guide/reference/`.")
        _upsert_agents_block!(agents, block)
        gitignore && _ensure_gitignored!(dir, ["/smlm-agent-guide/"])
        return bundle_dir
    end
end
